---
slug: :mikutter_growl_gntp
depends:
  mikutter: 3.1.0
  plugin:
  - settings
  - notify
version: '1.1.b'
author: maruTA_bis5
name: mikutter growl gntp
description: Show mikutter notifications via growl using gntp
